config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    resources :topics do
      resources :comments
    end

    root "topics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  # belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  default_scope { order(created_at: :desc)}
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comments, only: [:new,:create,:show,:update,:delete]
  def index
  end

  def new
    @comment = @topic.comments.new
  end

  def create
    @comment = @topic.comments.new(comment_params)
    @comment.save!
    redirect_to topic_path(@topic)
  end
  private

  def set_comments
    @topic = Topic.find(params[:topic_id])
  end

  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :topic_find, only: [:show, :edit, :update, :destroy]

  def index
    @topic = Topic.all
  end

  def show

  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to topics_path
    else
      render 'new'
    end
  end

  def edit
    if @topic.user != current_user
      redirect_to topic_path(@topic)
    end
  end

  def update
    if @topic.user == current_user
      @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to root_path
  end

  private

  def topic_find
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<%= form_for ([@topic,@topic.comments.build]) do |f| %>
  <p>
    <%= f.label :content, "Comment" %><br>
    <%= f.text_area :body, :class => 'commentbody' %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/new.html.erb
<%= render :partial => "comment" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada" rel="stylesheet">
  </head>


  <body>

    <div class = "heading">
      <h1> Forum </h1>
    </div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "Forum", root_path, :class => "navbar-brand"%>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><button class="btn navbar-btn"><%= link_to "New Post", new_topic_path%>
            </button></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to new_user_registration_path do %>
                <span class="glyphicon glyphicon-user"></span> Sign Up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Login
              <% end %>

            </li>
          </ul>
        </div>

      </nav>


<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
</p>

    <%= yield %>
  </body>
</html>

app/views/topics/edit.html.erb
<h1> Edit Topic </h1>

<%= form_for @topic do |f| %>

<p class="topic">
  <%= f.label :topic , :id => "titlehead"%><br>
  <%= f.text_field :title, :class => "title" %>
</p>

<p class="contentbody">
  <%= f.label :content %><br>
  <%= f.text_area :body, :class => "content" %>
</p>

<p class="submit">
  <%= f.submit :Create,:class => "btn btn-primary" %>
  <%= link_to "Cancel", root_path, :type => "button", :class => "btn btn-danger"%>
</p>

<%end%>

app/views/topics/index.html.erb
<div class= "col-sm-10 col-sm-offset-1">
  <div class="col-sm-8">
    <% @topic.each do |topic| %>
      <div class="well well-lg" id="main_topic">
        <%= link_to topic.title, topic %>
      </div>
    <% end %>
  </div>

  <div class="col-sm-3 col-sm-offset-1 well" id="sidenav">

  <h4>Categories</h4>

  </div>
</div>

app/views/topics/new.html.erb
<h2 id="newtopic"> New Topic </h2>

<%= form_for @topic do |f| %>

<p class="topic">
  <%= f.label :topic , :id => "titlehead"%><br>
  <%= f.text_field :title, :class => "title" %>
</p>

<p class="contentbody">
  <%= f.label :content %><br>
  <%= f.text_area :body, :class => "content" %>
</p>

<p class="submit">
  <%= f.submit :Create,:class => "btn btn-primary" %>
  <%= link_to "Cancel", root_path, :type => "button", :class => "btn btn-danger"%>
</p>

<%end%>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<p><%= @topic.body %></p>

<% if @topic.user == current_user %>
<%=link_to "Edit", edit_topic_path(@topic)%>
<% end %>

<br>

<h3>
  Reply
</h3>

<%= render :partial => 'comments/comment' %>


<%= link_to "Home", root_path%>
<%= link_to "Delete", topic_path(@topic),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %>

<br>

<% @topic.comments.all.each do |comment| %>

<%= comment.body %>

<% end %>